export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FESTIVAL_START = 'FESTIVAL_START';
export const FESTIVAL_SUBMIT = 'FESTIVAL_SUBMIT';
export const FESTIVAL_FINISH = 'FESTIVAL_FINISH';
export const FESTIVAL_FAIL = 'FESTIVAL_FAIL';