export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FESTIVAL_START = 'FESTIVAL_START';
export const GERENCIA_INIT_EDIT = 'GERENCIA_INIT_EDIT';
export const GERENCIA_EDIT_SAVE = 'GERENCIA_EDIT_SAVE';
export const FESTIVAL_SUBMIT = 'FESTIVAL_SUBMIT';
export const FESTIVAL_FINISH = 'FESTIVAL_FINISH';
export const FESTIVAL_FAIL = 'FESTIVAL_FAIL';

export const INSCRICAO_START = 'INSCRICAO_START';
export const FESTIVAL_LOAD = 'FESTIVAL_LOAD';
export const FESTIVAL_UNMOUNT = 'FESTIVAL_UNMOUNT';
export const INSCRICAO_UNMOUNT = 'INSCRICAO_UNMOUNT';